apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Local
    credentialsSecretRef:
      namespace: crossplane-system
      name: aws-creds