name: Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd
      
    - name: Log into ArgoCD
      run: |
        argocd login <ARGOCD_SERVER> --username <USERNAME> --password <PASSWORD>
      
    - name: Create Application
      run: |
        argocd app create my-app --repo <REPO_URL> --path <PATH_TO_MANIFESTS> --dest-server <DESTINATION_SERVER> --dest-namespace <NAMESPACE>
